### ISSUE TITLE
Failed to compile at Unity 2018.3 beta

### ISSUE THREAD

**Issue by optimisez** [laurenth-unity/Cinelights#1]
It seems like additionalLightData.ConvertPhysicalLightIntensityToLightIntensity() is removed at Unity 2018.3 beta with HDRP 4.0.1. I removed that to fix the compile error but I'm not sure whether it's the correct fix.

**Comment by laurenth-personal** [comment]
Hi, sorry I totally forgot to reply. I'll fix this, thanks for reporting.

**Comment by optimisez** [comment]
Seems like you are working on LightingTools. Is that even better tool than Cinelights?

**Comment by laurenth-personal** [comment]
I am trying to figure out a way to organize my code in a more modular way so several tools can share the same core and plug on top of it. So right now lighting tools contains cinelights. Ideally I'm move to packages with dependencies, but that's not finished at all so I'll update cinelights in the meantime

**Comment by laurenth-personal** [comment]
Now it compiles :)

**Comment by optimisez** [comment]
Btw @laurenth-unity, does this Windup project Light rig is done by you or somebody else? This tool looks really awesome that able to setup all the lighting in one inspector without needing to switch to another game object. 
![image](https://user-images.githubusercontent.com/7009368/48532320-e22e4d80-e8da-11e8-85b5-faa239b7949e.png)

**Comment by laurenth-personal** [comment]
I did that too, but it was built on an old version of cine lights so it broke, I'm pretty sure the code was a bit ugly so I didn't put it up, I'd need to spend some time redoing it.

**Comment by optimisez** [comment]
I see. Awesome.

**Comment by laurenth-personal** [comment]
Now you can see what I was cooking : the project now uses the packages LightingTools.Core and LightingTools.Cinelights so the scripts are no longer living in the projects, they are like features you can opt in by just adding them to your project.
Let me know how it goes if you get a chance to test it.

**Comment by optimisez** [comment]
Is that the expected output? 

![image](https://user-images.githubusercontent.com/7009368/48787727-52e2c900-ed24-11e8-80b2-a84a65488e7c.png)

**Comment by laurenth-personal** [comment]
it seems correct yes, the cine light tracks are in the groups on the timeline

**Comment by optimisez** [comment]
Btw how can I achieve the graphics of Windup project? It's so beautiful that until now I still have no idea how to achieve it.

**Comment by laurenth-personal** [comment]
Well we use HDRP and the cine lights, then you need great assets :) also quite a bit of time
